esphome:
  name_add_mac_suffix: false
  project:
    name: itsteddyyo.base
    version: "1.1"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain

api:
  reboot_timeout: 3min

ota:
  - platform: esphome
    password: !secret ota_password

logger:

improv_serial:

button:
- platform: restart
  name: Reboot
  entity_category: diagnostic
  disabled_by_default: true
- platform: safe_mode
  name: Safe Mode Boot
  entity_category: diagnostic
  disabled_by_default: true

dashboard_import:
  package_import_url: github://itsteddyyo/firmware/base.yaml@main
