esphome:
  name_add_mac_suffix: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret wifi_domain

api:
  reboot_timeout: 3min

logger:

ota:

improv_serial:

button:
- platform: restart
  name: Reboot
  entity_category: diagnostic
- platform: safe_mode
  name: Safe Mode Boot
  entity_category: diagnostic

dashboard_import:
  package_import_url: github://itsteddyyo/firmware/base.yaml@main
