esphome:
  project:
    name: itsteddyyo.ota
    version: "1.0"

ota:
  - platform: esphome
    password: !secret ota_password

dashboard_import:
  package_import_url: github://itsteddyyo/firmware/ota.yaml@main