substitutions:
  name: esp32-wroom

esphome:
  name: ${name}
  project:
    name: itsteddyyo.esp32-wroom
    version: "1.0"

dashboard_import:
  package_import_url: github://itsteddyyo/firmware/boards/esp32-wroom.yaml@main
