substitutions:
  name: esp32-wroom

esphome:
  name: ${name}
  project:
    name: itsteddyyo.esp32-wroom
  min_version: 2024.9.0

esp32:
  board: esp32dev
  framework:
    type: esp-idf

dashboard_import:
  package_import_url: github://itsteddyyo/firmware/boards/esp32-wroom.yaml@main
