substitutions:
  name: esp32_wroom

esphome:
  name: ${name}
  project:
    name: itsteddyyo.esp32_wroom
    version: "1.0"

dashboard_import:
  package_import_url: github://itsteddyyo/firmware/boards/esp32_wroom.yaml@main
