substitutions:
  name: m5stack_atom_lite

esphome:
  name: ${name}
  project:
    name: itsteddyyo.m5stack_atom_lite
    version: "1.0"

dashboard_import:
  package_import_url: github://itsteddyyo/firmware/boards/m5stack_atom_lite.yaml@main
