substitutions:
  name: m5stack-atom-lite

esphome:
  name: ${name}
  project:
    name: itsteddyyo.m5stack-atom-lite
    version: 1.0.0
  min_version: 2024.9.0

esp32:
  board: m5stack-atom
  framework:
    type: esp-idf

dashboard_import:
  package_import_url: github://itsteddyyo/firmware/boards/m5stack-atom-lite.yaml@main
