substitutions:
  name: m5stack-atom-lite

esphome:
  name: ${name}
  project:
    name: itsteddyyo.m5stack-atom-lite
    version: "1.0"

dashboard_import:
  package_import_url: github://itsteddyyo/firmware/boards/m5stack-atom-lite.yaml@main
