substitutions:
  bh1750_id: bh1750
  bh1750_i2c_address: "0x23"

esphome:
  project:
    name: itsteddyyo.light-sensor-bh1750
    version: 1.0.0
  min_version: 2024.9.0

i2c:
  - id: "bus_${bh1750_id}"
    scan: true
    sda: ${sda_pin}
    scl: ${scl_pin}

sensor:
  - platform: bh1750
    i2c_id: "bus_${bh1750_id}"
    name: "Illuminance"
    address: ${bh1750_i2c_address}
    update_interval: 2s
    accuracy_decimals: 0
    filters:
      - filter_out: nan
      - delta: 10%
      - round: 0

dashboard_import:
  package_import_url: github://itsteddyyo/firmware/sensors/light-sensor-bh1750.yaml@main
