substitutions:
  i2c_address: "0x23"

esphome:
  project:
    name: itsteddyyo.light-sensor-bh1750
    version: 1.0.0
  min_version: 2024.9.0

i2c:
  - id: bus_light
    scan: true
    sda: ${sda_pin}
    scl: ${scl_pin}

sensor:
  - platform: bh1750
    i2c_id: bus_light
    name: "Illuminance"
    address: ${i2c_address}
    update_interval: 1s
    accuracy_decimals: 0
    filters:
      - filter_out: nan
      - delta: 10%
      - round: 0

dashboard_import:
  package_import_url: github://itsteddyyo/firmware/sensors/light-sensor-bh1750.yaml@main
