substitutions:
  kincony_id: kincony
  kincony_delay: "0"
  kincony_inverted: "true"
  kincony_i2c_address: "0x24"

esphome:
  project:
    name: itsteddyyo.kincony-relay-switch
    version: 1.0.0
  min_version: 2024.9.0

globals:
  - id: delay_${name}
    type: int
    restore_value: no
    initial_value: '${kincony_delay}'

i2c:
  id: "bus_${kincony_id}"
  scan: true
  sda: ${sda_pin}
  scl:
    number: ${scl_pin}
    ignore_strapping_warning: true

pcf8574:
  id: "outputs_${kincony_id}"
  i2c_id: "bus_${kincony_id}"
  address: ${kincony_i2c_address}

switch:
  - platform: gpio
    id: ${name}
    name: ${friendly_name}
    pin:
      pcf8574: "outputs_${kincony_id}"
      number: ${gpio_pin}
      mode: OUTPUT
      inverted: ${kincony_inverted}
    on_turn_on:
      - if:
          condition:
            lambda: 'return id(delay_${name}) > 0;'
          then:
            - delay: "${kincony_delay}s"
            - switch.turn_off: ${name}

dashboard_import:
  package_import_url: github://itsteddyyo/firmware/sensors/kincony-relay-switch.yaml@main