substitutions:
  gpio_pin: GPIO26

esphome:
  project:
    name: itsteddyyo.laser-sensor
    version: "1.0"

binary_sensor:
  - platform: gpio
    pin: ${gpio_pin}
    name: Motion
    device_class: motion
    publish_initial_state: true
    filters:
      - invert: 
      - delayed_off: 1s

dashboard_import:
  package_import_url: github://itsteddyyo/firmware/sensors/laser-sensor.yaml@main