esphome:
  project:
    name: itsteddyyo.light-sensor
    version: 1.0.0
  min_version: 2024.9.0

i2c:
  sda: ${sda_pin}
  scl: ${scl_pin}
  scan: true
  id: bus_a

sensor:
  - platform: bh1750
    name: "Illuminance"
    address: 0x23
    update_interval: 1s
    accuracy_decimals: 0
    filters:
      - filter_out: nan
      - delta: 10%
      - round: 0

dashboard_import:
  package_import_url: github://itsteddyyo/firmware/sensors/light-sensor.yaml@main
