substitutions:
  sda_pin: GPIO21
  scl_pin: GPIO22

esphome:
  project:
    name: itsteddyyo.light-sensor
    version: "1.1"

i2c:
  sda: ${sda_pin}
  scl: ${scl_pin}
  scan: true
  id: bus_a

sensor:
  - platform: bh1750
    id: illuminance
    name: "Illuminance"
    address: 0x23
    update_interval: 1s
    accuracy_decimals: 0
    filters:
      - filter_out: nan
      - delta: 10%
      - round: 0

binary_sensor:
  - platform: template
    name: Light
    device_class: light
    lambda: |-
        if (id(illuminance).state > 20) {
          return true; 
        } else {
          return false; 
        }

dashboard_import:
  package_import_url: github://itsteddyyo/firmware/sensors/light-sensor.yaml@main
