esphome:
  project:
    name: itsteddyyo.soil-moisture-sensor
    version: 1.0.0
  min_version: 2024.9.0

# M5 Atom-Lite Grove port used to connect sensor, pin and sensor 
# calibraation may need updating for other platforms/ sensors
sensor:
  - platform: adc
    pin: ${adc_pin}
    name: Soil Moisture Value
    attenuation: 12db
    id: soil_moisture
    accuracy_decimals: 0
    device_class: moisture
    unit_of_measurement: "%"
    update_interval: 10s
    icon: mdi:flower
    filters:
      - clamp:
          min_value: 1.25
          max_value: 1.75
          ignore_out_of_range: false
      - sliding_window_moving_average:
          window_size: 15
          send_every: 15
      - median:
          window_size: 15
          send_every: 7
          send_first_at: 3
      - calibrate_linear:
        - 1.75 -> 0.0
        - 1.25 -> 100.0
 
# Timed switch for water pump - manually trigger water pump for specified time.
# Ajust delay to suit lenght of time the pump runs
# This was added to prevent the plant/ room getting drenched by an 
# accidental press of the switch emptying a whole water resevoir!
switch:
  - platform: gpio
    pin: ${gpio_pin}
    id: relay
    name: Water pump
    icon: "mdi:water"
    on_turn_on:
    - logger.log: "Pump Turned On!"
    - delay: 30s
    - switch.turn_off: relay
    - logger.log: "Pump Turned Off!"

dashboard_import:
  package_import_url: github://itsteddyyo/firmware/sensors/soil-moisture-sensor.yaml@main
