esphome:
    project:
        name: itsteddyyo.bluetooth-proxy
        version: 1.0.0
    min_version: 2024.9.0

esp32_ble_tracker:
    scan_parameters:
        active: true
        interval: 320ms # suggested 211ms # default 320ms
        window: 300ms # suggested 120ms # default 30ms

bluetooth_proxy:
    active: true

dashboard_import:
    package_import_url: github://itsteddyyo/firmware/sensors/_other/bluetooth-proxy.yaml@v2
