substitutions:
  ld2410_id: ld2410
  ld2410_delayed_on: 200ms
  ld2410_delayed_off: 2s

esphome:
  project:
    name: itsteddyyo.mmwave-sensor
    version: 1.0.0
  min_version: 2024.9.0

uart:
  - id: "${ld2410_id}_uart"
    tx_pin: ${tx_pin}
    rx_pin: ${rx_pin}
    baud_rate: 256000
    parity: NONE
    stop_bits: 1
 
ld2410:
  id: "${ld2410_id}_ld2410"
  uart_id: "${ld2410_id}_uart"

binary_sensor:
  - platform: ld2410
    has_moving_target:
      id: "${ld2410_id}_motion"
      name: Motion
  - platform: gpio
    id: "${ld2410_id}_occupancy"
    pin: ${gpio_pin}
    name: Occupancy
    device_class: occupancy
    publish_initial_state: true
    filters:
      - delayed_on: ${ld2410_delayed_on}
      - delayed_off: ${ld2410_delayed_off}

switch:
  - platform: ld2410
    engineering_mode:
      id: "${ld2410_id}_engineering"
      name: Engineering Mode
      restore_mode: ALWAYS_OFF
      disabled_by_default: true
    bluetooth:
      id: "${ld2410_id}_bluetooth"
      name: Bluetooth
      restore_mode: ALWAYS_OFF
      disabled_by_default: true

dashboard_import:
  package_import_url: github://itsteddyyo/firmware/sensors/uart/mmwave-sensor.yaml@v2
