substitutions:
  delayed_on: 200ms
  delayed_off: 2s

esphome:
  project:
    name: itsteddyyo.mmwave-sensor
    version: 1.0.0
  min_version: 2024.9.0

uart:
  - id: uart_mmwave
    tx_pin: ${tx_pin}
    rx_pin: ${rx_pin}
    baud_rate: 256000
    parity: NONE
    stop_bits: 1
 
ld2410:
  uart_id: uart_mmwave

binary_sensor:
  - platform: ld2410
    has_moving_target:
      name: Motion
  - platform: gpio
    pin: ${gpio_pin}
    name: Occupancy
    device_class: occupancy
    publish_initial_state: true
    filters:
      - delayed_on: ${delayed_on}
      - delayed_off: ${delayed_off}

switch:
  - platform: ld2410
    engineering_mode:
      name: Engineering Mode
    bluetooth:
      name: Bluetooth

dashboard_import:
  package_import_url: github://itsteddyyo/firmware/sensors/mmwave-sensor.yaml@main
